### ISSUE TITLE
about ChIP-exo paired bed files

### ISSUE THREAD

**Issue by mortunco** [steinmann/peakzilla#4]
Dear Jonas,

Thank you for coding such a great tool for peak calling. It will greatly
contribute to my graduate project.

I would like to ask couple questions. I would like to process a public GEO
dataset that contains chip-exo data. Each sample contains two bed files (
for paired ends reads). therefore can I use peakzilla to call peaks as it
was  advertised in the abstract of peakzilla paper ? If so could you
describe me how ? because in github tutorial there is only single end read
run is shown.

Best regards,

Tunc.

**Comment by mortunco** [comment]
I tried to send a mail to the email given however, I got delivery error so I had to ask my question as an issue.

Best,

Tunc.

**Comment by abardet** [comment]
Dear Tunc,

Sorry for the delay, I just moved and was disconnected for a while.

Peakzilla does take paired-end data as input in the BEDPE format with the -p option.

About the BEDPE format see http://bedtools.readthedocs.io/en/latest/content/general-usage.html

From a bam file that contains paired reads, you can do:
samtools sort -n sample.bam > sample_sortedByName.bam
bamToBed -bedpe -i sample_sortedByName.bam > sample.bedpe
peakzilla.py -p sample.bedpe > sample_peaks.tsv

If you have already two separate bed files (assuming that corresponding reads are on corresponding lines) try:
paste sample1.bed sample2.bed | awk -vOFS='\t' '{print $1,$2,$3,$7,$8,$9,$4,$5,$6,$12}' > sample.bedpe
peakzilla.py -p sample.bedpe > sample_peaks.tsv

Let me know if you have any questions.

Best,
Anaïs

**Comment by mortunco** [comment]
Dear Anaïs,

Thank you for your help and keeping up with the issue.

This solved my problem.

Best,

Tunc.
